language: python
python:
    - "2.7"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - build-essential
            - gfortran
            - g77
install:
    - pip install -r requirements.txt
    - FC=gfortran python setup.py install
script: pytest
